"""empty message

Revision ID: 64e6872940af
Revises: e659834f18de
Create Date: 2024-12-05 04:46:15.455521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e6872940af'
down_revision: Union[str, None] = 'e659834f18de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
