"""empty message

Revision ID: e659834f18de
Revises: a24c4aeabb84
Create Date: 2024-12-05 04:35:51.559058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e659834f18de'
down_revision: Union[str, None] = 'a24c4aeabb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('power_consumption', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('type', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('custom_power_consumption', sa.Integer(), nullable=True))
    op.drop_column('recipes', 'energy')
    op.drop_column('recipes', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('energy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'custom_power_consumption')
    op.drop_column('materials', 'type')
    op.drop_column('buildings', 'power_consumption')
    # ### end Alembic commands ###
